name: Compress files
run-name: Compressing files...
on: [push]
jobs:
  Compress:
    runs-on: ubuntu-latest
    steps:
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release.zip 35PokesShowdownFilter
