name: Compress files
run-name: Compressing files...
on: [push]
jobs:
  Compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: composer install --ansi --no-progress --no-interaction --prefer-dist
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release.zip dates
      - uses: actions/upload-artifact@v2
        with:
          name: vendor.zip
