name: Compress files
run-name: Compressing files...
on: [push]
jobs:
  Compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.2
        with:
          files: manifest.json
          dest: result.zip
