name: Compress files
run-name: Compressing files...
on: [push]
jobs:
  Compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.2
        with:
          files: manifest.json background.js dates/ images/ popup/ scripts/
          dest: release.zip
      - uses: actions/upload-artifact@v4
        with:
          name: release
          path: ${{ github.workspace }}/release.zip
